var s1 = '';
s1 += '<div class="mn-suspend" style="display:none;">';
s1 += '<dl>';
s1 += '<dt class="IE6PNG"></dt>';
s1 += '<dd class="suspendQQ ajaxkefuQQLink"></dd>';
s1 += '<dd class="suspendTel"><span class="ajaxkefuTel"></span></dd>';
s1 += '</dl>';
s1 += '</div>';
s1 += '';
document.write(s1);